<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>TechKidPro.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <ProjectReference Include="..\TechKidPro.Core\TechKidPro.Core.csproj" />
    <ProjectReference Include="..\TechKidPro.Data\TechKidPro.Data.csproj" />
    <ProjectReference Include="..\TechKidPro.Infrastructure\TechKidPro.Infrastructure.csproj" />
    <ProjectReference Include="..\TechKidPro.Services\TechKidPro.Services.csproj" />
  </ItemGroup>
</Project>
