<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>TechKidPro.Services</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TechKidPro.Core\TechKidPro.Core.csproj" />
    <ProjectReference Include="..\TechKidPro.Data\TechKidPro.Data.csproj" />
  </ItemGroup>
</Project>
