# -*- coding: utf-8 -*-
# Viết lại String, Tuple, Set theo từng thao tác (cùng khuôn với List và Dict trong sotay_content_ops.py)
from sotay_content_ops import OP

STR_TOPIC = dict(id="str", level=2, title="Chuỗi (str)", summary="Chuỗi là dãy ký tự **không thể sửa tại chỗ**. Học theo các thao tác: **tạo → truy cập → duyệt → nối/thêm → sửa → xóa → tìm → biến đổi → tách/nối → kiểm tra**.",
 blocks=[
  ("table", ["Thao tác", "Cú pháp chính"], [
    ["Tạo", "`\"abc\"`, `'abc'`, `\"\"\"nhiều dòng\"\"\"`, `str(123)`"],
    ["Truy cập", "`s[0]`, `s[-1]`, `s[1:4]`, `len(s)`"],
    ["Duyệt", "`for ch in s:`, `for i, ch in enumerate(s):`"],
    ["Nối / thêm", "`a + b`, `s * 3`, `f\"{x}\"`, `\"\".join(...)`"],
    ["Sửa", "`s.replace(a, b)`, `s[:i] + x + s[i+1:]`"],
    ["Xóa", "`s.replace(x, \"\")`, `s.strip()`, `s[1:]`"],
    ["Tìm", "`x in s`, `s.find(x)`, `s.count(x)`, `s.startswith(x)`"],
    ["Biến đổi", "`s.lower()`, `s.upper()`, `s.title()`"],
    ["Tách / nối", "`s.split()`, `\"-\".join(list)`"],
    ["Kiểm tra loại", "`s.isdigit()`, `s.isalpha()`, `s.isspace()`"],
  ]),
  OP("Thao tác 1 · Tạo chuỗi"),
  ("ex", "Các cách viết chuỗi", "a = \"Xin chao\"                 # nháy kép\nb = 'Python'                   # nháy đơn\nc = \"\"\"Dong 1\nDong 2\"\"\"                     # ba nháy: nhiều dòng\nd = \"Cau noi: \\\"Hi\\\"\\tHet\"         # \\\" nháy kép, \\t tab, \\n xuống dòng\nprint(a, b, sep=\" | \")\nprint(c)\nprint(d)\nprint(str(123) + str(4.5))     # ép kiểu số → chuỗi\nprint(\"ab\" * 3, len(\"\"))       # lặp chuỗi; chuỗi rỗng", {}),
  ("ex", "Nhập chuỗi từ bàn phím", "ten = input().strip()\nprint(\"Chao\", ten)", {"stdin": "  An  "}),
  OP("Thao tác 2 · Truy cập ký tự"),
  ("ex", "Chỉ số và độ dài", "s = \"Python\"\nprint(len(s))        # 6\nprint(s[0], s[-1])   # P n\nprint(s[2])          # t", {}),
  ("ex", "Cắt lát s[start:stop:step]", "s = \"0123456789\"\nprint(s[:4])      # 0123 (4 ký tự đầu)\nprint(s[-3:])     # 789 (3 ký tự cuối)\nprint(s[2:6])     # 2345\nprint(s[::2])     # 02468 (bước 2)\nprint(s[::-1])    # đảo ngược chuỗi", {}),
  ("warn", "`s[10]` khi chuỗi chỉ có 6 ký tự gây `IndexError`; riêng cắt lát `s[10:]` thì **không** lỗi, chỉ trả về chuỗi rỗng."),
  OP("Thao tác 3 · Duyệt từng ký tự"),
  ("ex", "Duyệt theo ký tự, theo chỉ số, và đếm", "s = \"banana\"\nfor ch in s:\n    print(ch, end=\" \")\nprint()\nfor i, ch in enumerate(s):\n    if ch == \"n\":\n        print(\"n ở chỉ số\", i)\ndem = 0\nfor ch in s:\n    if ch == \"a\":\n        dem += 1\nprint(dem)", {}),
  ("ex", "Đếm chữ cái, chữ số, ký tự khác", "s = \"Python 3.12!\"\nchu = so = khac = 0\nfor ch in s:\n    if ch.isalpha():\n        chu += 1\n    elif ch.isdigit():\n        so += 1\n    else:\n        khac += 1\nprint(chu, so, khac)", {}),
  OP("Thao tác 4 · Nối và thêm vào chuỗi"),
  ("ex", "Toán tử +, *, += và f-string", "ho, ten = \"Nguyen\", \"An\"\nprint(ho + \" \" + ten)        # nối bằng +\nprint(\"-\" * 10)              # lặp\ns = \"\"\nfor i in range(1, 6):\n    s += str(i) + \" \"         # nối dần trong vòng lặp\nprint(s.strip())\ntuoi = 16\nprint(f\"{ten} {tuoi} tuoi, sau 5 nam: {tuoi + 5}\")   # f-string", {}),
  ("ex", "Thêm vào đầu / giữa chuỗi (tạo chuỗi mới)", "s = \"Python\"\nprint(\">>> \" + s)               # thêm vào đầu\nprint(s[:2] + \"--\" + s[2:])      # chèn vào chỉ số 2", {}),
  ("tip", "Nối **nhiều** mảnh nên dùng `\"\".join(list)` — nhanh hơn nhiều so với `+=` trong vòng lặp lớn."),
  OP("Thao tác 5 · Thay đổi (sửa) nội dung"),
  ("warn", "Chuỗi bất biến: `s[0] = \"X\"` gây lỗi `TypeError`. Muốn đổi phải **tạo chuỗi mới** rồi gán lại."),
  ("ex", "Đổi một ký tự bằng cắt lát", "s = \"Python\"\ns = \"J\" + s[1:]               # thay ký tự đầu\nprint(s)\nvt = 2\ns = s[:vt] + \"T\" + s[vt + 1:]     # thay ký tự ở chỉ số vt\nprint(s)", {}),
  ("ex", "replace(): thay thế mọi chỗ khớp", "s = \"banana\"\nprint(s.replace(\"a\", \"o\"))\nprint(s.replace(\"a\", \"o\", 2))   # chỉ thay 2 lần đầu", {}),
  ("ex", "Sửa từng ký tự: chuyển sang list rồi ghép lại", "s = \"hello\"\nl = list(s)\nl[0] = \"J\"\nl[-1] = \"y\"\nprint(\"\".join(l))", {}),
  OP("Thao tác 6 · Xóa ký tự / đoạn"),
  ("ex", "Xóa khoảng trắng hai đầu: strip()", "s = \"   xin chao  \"\nprint(\"[\" + s.strip() + \"]\")\nprint(\"[\" + s.lstrip() + \"]\", \"[\" + s.rstrip() + \"]\")", {}),
  ("ex", "Xóa ký tự bằng replace hoặc cắt lát", "s = \"a-b-c\"\nprint(s.replace(\"-\", \"\"))         # bỏ mọi dấu '-'\nt = \"Python\"\nprint(t[1:])                      # bỏ ký tự đầu\nprint(t[:-1])                     # bỏ ký tự cuối\nprint(t[:2] + t[3:])              # bỏ ký tự ở chỉ số 2", {}),
  ("ex", "Giữ lại ký tự thỏa điều kiện (bỏ chữ số)", "s = \"a1b2c3\"\nprint(\"\".join(ch for ch in s if not ch.isdigit()))", {}),
  OP("Thao tác 7 · Tìm kiếm & kiểm tra"),
  ("ex", "in, find, index, count", "s = \"hello world\"\nprint(\"world\" in s)         # có chứa không?\nprint(s.find(\"o\"))           # vị trí đầu tiên (không có: -1)\nprint(s.find(\"z\"))\nprint(s.rfind(\"o\"))          # vị trí cuối cùng\nprint(s.count(\"l\"))          # số lần xuất hiện\nprint(s.startswith(\"he\"), s.endswith(\"ld\"))", {}),
  ("ex", "Tìm mọi vị trí xuất hiện", "s = \"abracadabra\"\nvt = []\nfor i in range(len(s)):\n    if s[i] == \"a\":\n        vt.append(i)\nprint(vt)", {}),
  ("warn", "`s.index(x)` báo `ValueError` nếu không thấy; `s.find(x)` trả về `-1`. Dùng `find` khi chưa chắc có."),
  OP("Thao tác 8 · Biến đổi chữ hoa / thường"),
  ("ex", "lower, upper, title, capitalize", "s = \"nGuyen van AN\"\nprint(s.lower())\nprint(s.upper())\nprint(s.title())          # Hoa chữ đầu mỗi từ\nprint(s.capitalize())     # chỉ Hoa chữ đầu câu\nprint(\"aBc\".swapcase())", {}),
  ("ex", "Chuẩn hóa họ tên", "ten = \"  nGUYEN   van   an \"\nprint(\" \".join(w.capitalize() for w in ten.split()))", {}),
  OP("Thao tác 9 · Tách và nối chuỗi"),
  ("ex", "split(): tách thành list", "print(\"an binh chi\".split())          # theo khoảng trắng\nprint(\"2026-10-05\".split(\"-\"))        # theo ký tự chỉ định\nprint(\"a,b,c,d\".split(\",\", 2))         # tối đa 2 lần tách\nprint(\"dong1\\ndong2\".splitlines())", {}),
  ("ex", "join(): nối list thành chuỗi", "ds = [\"an\", \"binh\", \"chi\"]\nprint(\"-\".join(ds))\nprint(\" \".join(str(x) for x in [1, 2, 3]))   # phần tử phải là chuỗi\nprint(\"\".join(reversed(\"abc\")))", {}),
  OP("Thao tác 10 · Kiểm tra loại ký tự & mã ký tự"),
  ("ex", "isdigit, isalpha, isalnum, isspace, isupper", "print(\"123\".isdigit(), \"abc\".isalpha(), \"ab1\".isalnum())\nprint(\"  \".isspace(), \"ABC\".isupper(), \"abc\".islower())", {}),
  ("ex", "ord() và chr(): ký tự ↔ mã ASCII", "print(ord(\"A\"), ord(\"a\"), ord(\"0\"))\nprint(chr(66), chr(98))\nprint(chr(ord(\"a\") + 2))        # dịch chữ cái đi 2", {}),
  OP("Tổng hợp & ví dụ ứng dụng"),
  ("table", ["Phương thức", "Tác dụng", "Ví dụ → kết quả"], [
    ["`.strip()`", "Xóa khoảng trắng hai đầu", "`\" a \".strip()` → `\"a\"`"],
    ["`.lower()` `.upper()`", "Chữ thường / HOA", "`\"Ab\".upper()` → `\"AB\"`"],
    ["`.title()` `.capitalize()`", "Hoa chữ đầu mỗi từ / chữ đầu", "`\"an binh\".title()` → `\"An Binh\"`"],
    ["`.split()`", "Tách thành list các từ", "`\"a b\".split()` → `['a', 'b']`"],
    ["`\"-\".join(list)`", "Nối list thành chuỗi", "`\"-\".join(['a','b'])` → `\"a-b\"`"],
    ["`.replace(a, b)`", "Thay a bằng b", "`\"aab\".replace(\"a\",\"x\")` → `\"xxb\"`"],
    ["`.find(x)`", "Vị trí đầu tiên (không thấy: `-1`)", "`\"hello\".find(\"l\")` → `2`"],
    ["`.count(x)`", "Đếm số lần xuất hiện", "`\"banana\".count(\"a\")` → `3`"],
    ["`.startswith(x)` `.endswith(x)`", "Bắt đầu / kết thúc bằng x", "`\"abc\".startswith(\"a\")` → `True`"],
    ["`.isdigit()` `.isalpha()`", "Toàn chữ số / toàn chữ cái", "`\"123\".isdigit()` → `True`"],
  ]),
  ("ex", "Kiểm tra chuỗi đối xứng (Palindrome)", "s = \"Madam\".lower()\nprint(s == s[::-1])", {}),
  ("ex", "Đếm số từ và từ dài nhất", "cau = \"hoc python that vui va huu ich\"\ntu = cau.split()\nprint(len(tu), max(tu, key=len))", {}),
 ])

TUPLE_TOPIC = dict(id="tuple", level=2, title="Tuple (bộ)", summary="Tuple `( )` là dãy có thứ tự **bất biến** (không sửa được sau khi tạo). Học theo các thao tác: **tạo → truy cập → duyệt → \"thêm / sửa / xóa\" → giải nén → tìm**.",
 blocks=[
  ("table", ["Thao tác", "Cú pháp chính"], [
    ["Tạo", "`t = (1, 2, 3)`, `(5,)`, `tuple(list)`"],
    ["Truy cập", "`t[0]`, `t[-1]`, `t[1:3]`, `len(t)`"],
    ["Duyệt", "`for x in t:`, `for i, x in enumerate(t):`"],
    ["Thêm / sửa / xóa", "**Không có** — tạo tuple mới bằng `+`, cắt lát hoặc đổi qua list"],
    ["Giải nén", "`x, y = t`, `a, *rest = t`"],
    ["Tìm / thống kê", "`x in t`, `t.index(x)`, `t.count(x)`, `min/max/sum`"],
  ]),
  ("p", "Dùng tuple khi dữ liệu **không nên thay đổi** (tọa độ, ngày tháng, cặp khóa) — tuple dùng được làm **khóa của dict** và phần tử của set, còn list thì không."),
  OP("Thao tác 1 · Tạo tuple"),
  ("ex", "Các cách tạo tuple", "a = (10, 20, 30)\nb = 10, 20, 30            # dấu ngoặc có thể bỏ\nc = (5,)                   # tuple 1 phần tử: BẮT BUỘC có dấu phẩy\nd = ()                     # tuple rỗng\ne = tuple([1, 2, 3])       # từ list\nf = tuple(\"abc\")           # từ chuỗi\nprint(a, b, c, d, e, f, sep=\"\\n\")\nprint(type((5)), type((5,)))", {}),
  OP("Thao tác 2 · Truy cập phần tử"),
  ("ex", "Chỉ số và cắt lát (giống list)", "t = (10, 20, 30, 40, 50)\nprint(t[0], t[-1], len(t))\nprint(t[1:4])      # cắt lát cho ra tuple mới\nprint(t[::-1])", {}),
  OP("Thao tác 3 · Duyệt tuple"),
  ("ex", "Duyệt giá trị và chỉ số", "t = (\"An\", \"Binh\", \"Chi\")\nfor x in t:\n    print(x)\nfor i, x in enumerate(t):\n    print(i, x)", {}),
  ("ex", "Duyệt list các tuple (rất hay gặp)", "hs = [(\"An\", 8.5), (\"Binh\", 9.0), (\"Chi\", 7.0)]\nfor ten, diem in hs:       # giải nén ngay trong for\n    print(ten, diem)", {}),
  OP("Thao tác 4 · Thêm, sửa, xóa — tạo tuple mới"),
  ("warn", "Tuple **không sửa tại chỗ**: `t[0] = 5` gây `TypeError`, và tuple cũng không có `append`, `remove`, `pop`."),
  ("ex", "Thêm: nối bằng +", "t = (1, 2, 3)\nt = t + (4,)               # (4,) có dấu phẩy\nprint(t)\nprint(t * 2)               # lặp", {}),
  ("ex", "Sửa và xóa bằng cắt lát", "t = (10, 20, 30, 40)\nvt = 1\nsua = t[:vt] + (99,) + t[vt + 1:]     # thay phần tử chỉ số 1\nprint(sua)\nxoa = t[:vt] + t[vt + 1:]              # xóa phần tử chỉ số 1\nprint(xoa)", {}),
  ("ex", "Cách gọn: đổi sang list, sửa, đổi lại tuple", "t = (3, 1, 2)\nl = list(t)\nl.append(9)\nl.sort()\nt = tuple(l)\nprint(t)", {}),
  OP("Thao tác 5 · Giải nén (unpacking)"),
  ("ex", "Gán nhiều biến cùng lúc, hoán đổi", "p = (10, 20)\nx, y = p\nprint(x, y)\nx, y = y, x               # hoán đổi nhờ tuple\nprint(x, y)", {}),
  ("ex", "Dấu * gom phần còn lại", "t = (1, 2, 3, 4, 5)\nd, *giua, c = t\nprint(d, giua, c)", {}),
  ("ex", "Hàm trả về nhiều giá trị (thực chất là tuple)", "def min_max(a):\n    return min(a), max(a)\n\nkq = min_max([4, 9, 2, 7])\nprint(kq, type(kq))\nthap, cao = min_max([4, 9, 2, 7])\nprint(thap, cao)", {}),
  OP("Thao tác 6 · Tìm kiếm & thống kê"),
  ("ex", "in, index, count và hàm thống kê", "t = (5, 2, 9, 2, 7)\nprint(2 in t)\nprint(t.index(9))          # vị trí đầu tiên\nprint(t.count(2))          # số lần xuất hiện\nprint(len(t), sum(t), min(t), max(t))", {}),
  OP("Thao tác 7 · Sắp xếp, so sánh, dùng làm khóa"),
  ("ex", "sorted() trả về list; so sánh tuple theo từng phần tử", "t = (5, 2, 9, 1)\nprint(sorted(t))           # kết quả là list\nprint(tuple(sorted(t)))\nprint((1, 5) < (2, 0), (3, 1) < (3, 2))   # so từng phần tử từ trái sang", {}),
  ("ex", "Tuple làm khóa của dict (tọa độ)", "ban_do = {(0, 0): \"nha\", (1, 2): \"cho\", (3, 4): \"truong\"}\nprint(ban_do[(1, 2)])\nprint((3, 4) in ban_do)", {}),
 ])

SET_TOPIC = dict(id="set", level=2, title="Set (tập hợp)", summary="Set `{ }` chứa các phần tử **không trùng lặp, không có thứ tự**; kiểm tra `in` rất nhanh `O(1)`. Học theo các thao tác: **tạo → truy cập → duyệt → thêm → sửa → xóa → kiểm tra → phép toán tập hợp**.",
 blocks=[
  ("table", ["Thao tác", "Cú pháp chính"], [
    ["Tạo", "`{1, 2, 3}`, `set()`, `set(list)`"],
    ["Truy cập / kiểm tra", "`x in s`, `len(s)` — **không có** chỉ số `s[0]`"],
    ["Duyệt", "`for x in s:`, `for x in sorted(s):`"],
    ["Thêm", "`s.add(x)`, `s.update(dãy)`"],
    ["Sửa", "xóa phần tử cũ rồi thêm phần tử mới"],
    ["Xóa", "`s.remove(x)`, `s.discard(x)`, `s.pop()`, `s.clear()`"],
    ["Quan hệ", "`A <= B`, `A.issubset(B)`, `A.isdisjoint(B)`"],
    ["Phép toán", "`A | B`, `A & B`, `A - B`, `A ^ B`"],
  ]),
  OP("Thao tác 1 · Tạo set"),
  ("ex", "Các cách tạo set", "a = {3, 1, 2, 3, 1}        # phần tử trùng tự bị loại\nb = set([5, 5, 6])         # từ list\nc = set(\"hello\")           # từ chuỗi: các ký tự khác nhau\nd = set()                  # set rỗng\nprint(a, b, sorted(c), d)\nprint(type({}), type(set()))", {}),
  ("warn", "`{}` là **dict rỗng**, không phải set rỗng. Muốn set rỗng phải viết `set()`."),
  ("ex", "Loại phần tử trùng và đếm số phần tử khác nhau", "ids = [101, 102, 101, 103, 102]\nprint(set(ids))\nprint(len(set(ids)))        # số phần tử khác nhau", {}),
  OP("Thao tác 2 · Truy cập & kiểm tra phần tử"),
  ("ex", "Set không có chỉ số — dùng in và len", "s = {10, 20, 30}\nprint(20 in s, 99 in s)\nprint(len(s))\n# s[0]   # lỗi TypeError: set không có thứ tự nên không có chỉ số\nprint(min(s), max(s), sum(s))", {}),
  ("tip", "Kiểm tra `x in set` là `O(1)`, còn `x in list` là `O(N)`. Cần tra cứu nhiều lần → đổi list sang set."),
  OP("Thao tác 3 · Duyệt set"),
  ("ex", "Duyệt các phần tử (thứ tự không đảm bảo, nên sắp xếp khi in)", "s = {5, 1, 9, 3}\nfor x in sorted(s):\n    print(x, end=\" \")\nprint()\nprint([x * x for x in sorted(s)])", {}),
  OP("Thao tác 4 · Thêm phần tử"),
  ("ex", "add(): thêm một phần tử", "s = {1, 2}\ns.add(3)\ns.add(2)                  # đã có → không thay đổi\nprint(s)", {}),
  ("ex", "update(): thêm nhiều phần tử từ list, tuple, set khác", "s = {1, 2}\ns.update([3, 4, 4])\ns.update({5}, (6, 7))\nprint(s)", {}),
  ("ex", "Xây set dần trong vòng lặp: các chữ số khác nhau của số", "n = 1223334\nso = set()\nwhile n > 0:\n    so.add(n % 10)\n    n //= 10\nprint(sorted(so), len(so))", {}),
  OP("Thao tác 5 · Thay đổi (sửa) phần tử"),
  ("tip", "Phần tử của set **không sửa trực tiếp** được (không có chỉ số). Muốn đổi `a` thành `b`: xóa `a` rồi thêm `b`."),
  ("ex", "Đổi 3 thành 30", "s = {1, 2, 3}\ns.discard(3)\ns.add(30)\nprint(s)", {}),
  ("ex", "Biến đổi mọi phần tử bằng set comprehension", "s = {1, 2, 3, 4}\nbinh_phuong = {x * x for x in s}\nprint(binh_phuong)\nchan = {x for x in s if x % 2 == 0}\nprint(chan)", {}),
  OP("Thao tác 6 · Xóa phần tử"),
  ("ex", "discard() và remove()", "s = {1, 2, 3, 4}\ns.discard(2)       # không có cũng KHÔNG báo lỗi\ns.discard(99)\nprint(s)\ns.remove(3)        # không có thì báo KeyError\nprint(s)", {}),
  ("ex", "pop() và clear()", "s = {7}\nx = s.pop()        # lấy ra một phần tử bất kỳ\nprint(x, s)\ns2 = {1, 2, 3}\ns2.clear()\nprint(s2, len(s2))", {}),
  OP("Thao tác 7 · Phép toán tập hợp"),
  ("ex", "Hợp, giao, hiệu, hiệu đối xứng", "A = {1, 2, 3, 4}\nB = {3, 4, 5, 6}\nprint(A | B)   # hợp: có ở A hoặc B\nprint(A & B)   # giao: có ở cả A và B\nprint(A - B)   # hiệu: có ở A mà không có ở B\nprint(A ^ B)   # hiệu đối xứng: chỉ ở một trong hai", {}),
  ("ex", "Dạng phương thức và cập nhật tại chỗ", "A = {1, 2, 3}\nB = {3, 4}\nprint(A.union(B), A.intersection(B), A.difference(B))\nA |= B          # A = A | B\nprint(A)", {}),
  ("ex", "Bài toán: học sinh học cả hai môn / chỉ một môn", "toan = {\"An\", \"Binh\", \"Chi\"}\ntin = {\"Binh\", \"Chi\", \"Dung\"}\nprint(sorted(toan & tin))\nprint(sorted(toan ^ tin))\nprint(sorted(toan | tin))", {}),
  OP("Thao tác 8 · Quan hệ giữa các tập"),
  ("ex", "Tập con, tập cha, rời nhau", "A = {1, 2}\nB = {1, 2, 3}\nprint(A <= B, A.issubset(B))        # A là tập con của B?\nprint(B >= A, B.issuperset(A))\nprint(A.isdisjoint({7, 8}))         # không có phần tử chung?", {}),
  OP("Tổng hợp & mẹo ứng dụng"),
  ("ex", "Loại trùng nhưng giữ nguyên thứ tự xuất hiện", "a = [3, 1, 3, 2, 1, 4]\nprint(list(dict.fromkeys(a)))", {}),
  ("ex", "Tìm phần tử xuất hiện ở cả hai danh sách", "a = [1, 2, 3, 4, 5]\nb = [4, 5, 6, 7]\nprint(sorted(set(a) & set(b)))", {}),
  ("ex", "Phát hiện có phần tử trùng trong list", "a = [4, 7, 1, 9, 7]\nprint(len(set(a)) < len(a))", {}),
  ("tip", "Phần tử của set phải là kiểu **bất biến** (số, chuỗi, tuple). Không bỏ `list` hay `dict` vào set được."),
 ])
