# -*- coding: utf-8 -*-
# Viết lại hai chủ đề List và Dict theo từng THAO TÁC: tạo → truy cập → duyệt → thêm → sửa → xóa → tìm/kiểm tra → ...
# Khối ("h", "op", tiêu đề) là thanh tiêu đề của một thao tác.

def OP(t):
    return ("h", "op", t)

LIST_TOPIC = dict(id="list", level=2, title="Danh sách (list)", summary="List là dãy có thứ tự, **sửa được**, chứa nhiều kiểu dữ liệu. Học theo các thao tác: **tạo → truy cập → duyệt → thêm → sửa → xóa → tìm → sắp xếp → sao chép**.",
 blocks=[
  ("table", ["Thao tác", "Cú pháp chính"], [
    ["Tạo", "`a = [1, 2, 3]`, `list(range(5))`, `[]`"],
    ["Truy cập", "`a[0]`, `a[-1]`, `a[1:3]`, `len(a)`"],
    ["Duyệt", "`for x in a:`, `for i, x in enumerate(a):`"],
    ["Thêm", "`a.append(x)`, `a.insert(i, x)`, `a.extend(b)`"],
    ["Sửa", "`a[i] = x`, `a[1:3] = [...]`"],
    ["Xóa", "`a.pop()`, `a.remove(x)`, `del a[i]`, `a.clear()`"],
    ["Tìm / kiểm tra", "`x in a`, `a.index(x)`, `a.count(x)`"],
    ["Sắp xếp / đảo", "`a.sort()`, `sorted(a)`, `a.reverse()`"],
  ]),
  OP("Thao tác 1 · Tạo danh sách"),
  ("ex", "Các cách tạo list", "a = [5, 2, 9, 1]              # liệt kê phần tử\nb = []                         # list rỗng\nc = list(range(1, 6))          # từ dãy số\nd = [0] * 5                    # 5 phần tử bằng 0\ne = [\"An\", 16, True, 3.5]      # nhiều kiểu dữ liệu\nprint(a, b, c, d, e)", {}),
  ("ex", "Nhập list từ bàn phím", "a = list(map(int, input().split()))\nprint(a, len(a))", {"stdin": "5 2 9 1"}),
  OP("Thao tác 2 · Truy cập phần tử"),
  ("ex", "Chỉ số dương, chỉ số âm và độ dài", "a = [10, 20, 30, 40, 50]\nprint(a[0])        # phần tử đầu (chỉ số bắt đầu từ 0)\nprint(a[-1])       # phần tử cuối\nprint(a[-2])       # phần tử thứ hai từ cuối\nprint(len(a))      # số phần tử", {}),
  ("ex", "Cắt lát [bắt đầu : kết thúc : bước]", "a = [10, 20, 30, 40, 50]\nprint(a[1:4])      # chỉ số 1, 2, 3 (không gồm 4)\nprint(a[:2])       # từ đầu đến trước chỉ số 2\nprint(a[2:])       # từ chỉ số 2 đến hết\nprint(a[::2])      # cách một phần tử\nprint(a[::-1])     # đảo ngược", {}),
  ("warn", "Truy cập chỉ số ngoài phạm vi (`a[5]` khi `len(a) == 5`) gây `IndexError`. Chỉ số hợp lệ là `0` … `len(a) - 1`."),
  OP("Thao tác 3 · Duyệt danh sách"),
  ("ex", "Duyệt theo giá trị", "a = [5, 2, 9]\nfor x in a:\n    print(x)", {}),
  ("ex", "Duyệt theo chỉ số", "a = [5, 2, 9]\nfor i in range(len(a)):\n    print(\"a[\" + str(i) + \"] =\", a[i])", {}),
  ("ex", "Duyệt lấy cả chỉ số và giá trị: enumerate", "a = [5, 2, 9]\nfor i, x in enumerate(a):\n    print(i, x)\nfor i, x in enumerate(a, start=1):   # đánh số từ 1\n    print(i, x)", {}),
  ("ex", "Duyệt hai list song song: zip", "ten = [\"An\", \"Binh\", \"Chi\"]\ndiem = [8, 9, 7]\nfor t, d in zip(ten, diem):\n    print(t, d)", {}),
  OP("Thao tác 4 · Thêm phần tử"),
  ("ex", "append: thêm vào cuối", "a = [1, 2, 3]\na.append(4)\nprint(a)", {}),
  ("ex", "insert: chèn vào vị trí bất kỳ", "a = [1, 2, 3]\na.insert(0, 99)     # chèn 99 vào đầu\na.insert(2, 50)     # chèn 50 vào chỉ số 2\nprint(a)", {}),
  ("ex", "extend và +: nối thêm nhiều phần tử", "a = [1, 2]\na.extend([3, 4])    # nối trực tiếp vào a\nprint(a)\nb = a + [5, 6]      # tạo list mới\nprint(b)", {}),
  ("ex", "Tạo list bằng cách thêm dần trong vòng lặp", "binh_phuong = []\nfor i in range(1, 6):\n    binh_phuong.append(i * i)\nprint(binh_phuong)", {}),
  ("tip", "`append` thêm **một** phần tử (kể cả là list); `extend` thêm **từng phần tử** của một dãy. So sánh: `[1].append([2, 3])` → `[1, [2, 3]]`, còn `[1].extend([2, 3])` → `[1, 2, 3]`."),
  OP("Thao tác 5 · Thay đổi (sửa) phần tử"),
  ("ex", "Gán lại một phần tử", "a = [5, 2, 9, 1]\na[1] = 99\nprint(a)\na[-1] += 10        # cộng thêm vào phần tử cuối\nprint(a)", {}),
  ("ex", "Sửa nhiều phần tử một lúc bằng cắt lát", "a = [1, 2, 3, 4, 5]\na[1:3] = [20, 30]\nprint(a)", {}),
  ("ex", "Biến đổi mọi phần tử (nhân đôi)", "a = [1, 2, 3, 4]\nfor i in range(len(a)):\n    a[i] = a[i] * 2      # phải dùng chỉ số mới sửa được list\nprint(a)", {}),
  ("warn", "Trong `for x in a: x = x * 2` chỉ đổi biến `x`, **không** đổi phần tử trong `a`. Muốn sửa phần tử phải gán qua chỉ số `a[i] = ...`."),
  OP("Thao tác 6 · Xóa phần tử"),
  ("ex", "pop: xóa theo vị trí (và lấy giá trị ra)", "a = [10, 20, 30, 40]\ncuoi = a.pop()        # xóa phần tử cuối\nprint(cuoi, a)\nvt1 = a.pop(1)        # xóa phần tử chỉ số 1\nprint(vt1, a)", {}),
  ("ex", "remove: xóa theo giá trị (lần xuất hiện đầu tiên)", "a = [3, 7, 3, 9]\na.remove(3)\nprint(a)", {}),
  ("ex", "del: xóa theo chỉ số hoặc đoạn; clear: xóa hết", "a = [1, 2, 3, 4, 5, 6]\ndel a[0]\nprint(a)\ndel a[1:3]\nprint(a)\na.clear()\nprint(a)", {}),
  ("ex", "Xóa mọi phần tử thỏa điều kiện (tạo list mới)", "a = [1, 2, 3, 4, 5, 6]\na = [x for x in a if x % 2 != 0]    # giữ lại số lẻ\nprint(a)", {}),
  ("warn", "Không xóa phần tử trong lúc `for x in a:` trên chính list đó — Python sẽ **bỏ sót phần tử**. Hãy tạo list mới như ví dụ trên."),
  OP("Thao tác 7 · Tìm kiếm & kiểm tra"),
  ("ex", "Kiểm tra có mặt, vị trí, số lần", "a = [5, 2, 9, 1, 5]\nprint(5 in a)            # có trong list không?\nprint(a.index(9))        # vị trí xuất hiện đầu tiên\nprint(a.count(5))        # số lần xuất hiện\nif 7 not in a:\n    print(\"không có 7\")", {}),
  ("ex", "Hàm thống kê có sẵn", "a = [5, 2, 9, 1, 5]\nprint(len(a), sum(a), min(a), max(a))", {}),
  ("warn", "`a.index(x)` báo `ValueError` nếu `x` không có. Hãy kiểm tra `x in a` trước."),
  OP("Thao tác 8 · Sắp xếp & đảo ngược"),
  ("ex", "sort() sửa tại chỗ, sorted() trả list mới", "a = [5, 2, 9, 1]\nprint(sorted(a))                 # tăng dần, a không đổi\nprint(sorted(a, reverse=True))   # giảm dần\na.sort()                         # a bị thay đổi\nprint(a)", {}),
  ("ex", "Sắp xếp theo tiêu chí riêng (key)", "ten = [\"binh\", \"an\", \"cuong\"]\nten.sort(key=len)               # theo độ dài\nprint(ten)", {}),
  ("ex", "Đảo ngược", "a = [1, 2, 3]\nprint(a[::-1])     # list mới\na.reverse()         # đảo tại chỗ\nprint(a)", {}),
  OP("Thao tác 9 · Sao chép & ghép"),
  ("ex", "Sao chép đúng cách", "a = [1, 2, 3]\nb = a            # KHÔNG phải bản sao: cùng một list\nc = a.copy()     # bản sao thật\nb.append(99)\nprint(a, c)", {}),
  ("warn", "Sao chép list: `b = a` **không** tạo bản sao (cùng một danh sách). Dùng `b = a.copy()` hoặc `b = a[:]`."),
  ("ex", "Nối và lặp list", "print([1, 2] + [3])\nprint([0] * 4)", {}),
  OP("Tổng hợp & mở rộng"),
  ("table", ["Phương thức", "Tác dụng", "Độ phức tạp"], [
    ["`.append(x)`", "Thêm x vào cuối", "O(1)"],
    ["`.insert(i, x)`", "Chèn x vào vị trí i", "O(N)"],
    ["`.pop()` / `.pop(i)`", "Xóa & trả về phần tử cuối / tại i", "O(1) / O(N)"],
    ["`.remove(x)`", "Xóa phần tử x đầu tiên", "O(N)"],
    ["`.index(x)`", "Vị trí của x (không có: báo lỗi)", "O(N)"],
    ["`.count(x)`", "Đếm số lần x xuất hiện", "O(N)"],
    ["`.sort()`", "Sắp xếp tại chỗ", "O(N log N)"],
    ["`.reverse()`", "Đảo ngược tại chỗ", "O(N)"],
    ["`sorted(a)`", "Trả về list mới đã sắp xếp", "O(N log N)"],
  ]),
  ("ex", "Danh sách 2 chiều (ma trận)", "m = [[1, 2, 3], [4, 5, 6]]\nprint(m[1][2])        # hàng 1, cột 2\nfor hang in m:\n    print(hang)", {}),
  ("warn", "Ma trận: **không** viết `[[0] * 3] * 2` (các hàng dùng chung). Hãy dùng `[[0] * 3 for _ in range(2)]`."),
 ])

DICT_TOPIC = dict(id="dict", level=2, title="Từ điển (dict)", summary="Dict lưu các cặp **khóa → giá trị**; tra cứu theo khóa rất nhanh `O(1)`. Học theo các thao tác: **tạo → truy cập → duyệt → thêm → sửa → xóa → kiểm tra → gộp**.",
 blocks=[
  ("table", ["Thao tác", "Cú pháp chính"], [
    ["Tạo", "`d = {\"a\": 1}`, `{}`, `dict(a=1)`"],
    ["Truy cập", "`d[k]`, `d.get(k, mac_dinh)`"],
    ["Duyệt", "`for k in d:`, `d.items()`, `d.values()`"],
    ["Thêm / sửa", "`d[k] = v`, `d.update(...)`, `d.setdefault(k, v)`"],
    ["Xóa", "`d.pop(k)`, `del d[k]`, `d.clear()`"],
    ["Kiểm tra", "`k in d`, `len(d)`"],
    ["Gộp / sao chép", "`d1 | d2`, `d.copy()`"],
  ]),
  ("p", "**Khóa** phải là kiểu bất biến (chuỗi, số, tuple) và **không trùng nhau**; **giá trị** có thể là bất kỳ kiểu gì (kể cả list, dict)."),
  OP("Thao tác 1 · Tạo từ điển"),
  ("ex", "Các cách tạo dict", "sv = {\"ten\": \"An\", \"tuoi\": 16}        # liệt kê cặp khóa: giá trị\nrong = {}                                # dict rỗng\nd2 = dict(ten=\"Binh\", tuoi=17)           # dùng dict()\nd3 = dict(zip([\"a\", \"b\"], [1, 2]))       # ghép hai list\nd4 = {x: x * x for x in range(1, 5)}     # dict comprehension\nprint(sv, rong, d2, d3, d4, sep=\"\\n\")", {}),
  OP("Thao tác 2 · Truy cập giá trị"),
  ("ex", "Truy cập bằng khóa", "sv = {\"ten\": \"An\", \"tuoi\": 16}\nprint(sv[\"ten\"])\nprint(len(sv))        # số cặp khóa-giá trị", {}),
  ("ex", "get(): lấy an toàn, không báo lỗi", "d = {\"a\": 1}\nprint(d.get(\"a\"))        # 1\nprint(d.get(\"b\"))        # None — khóa không có\nprint(d.get(\"b\", 0))     # 0 — giá trị mặc định tự đặt", {}),
  ("warn", "`d[\"b\"]` khi khóa `\"b\"` không tồn tại gây `KeyError`. Dùng `d.get(\"b\", mac_dinh)` hoặc kiểm tra `\"b\" in d` trước."),
  OP("Thao tác 3 · Duyệt từ điển"),
  ("ex", "Duyệt khóa (mặc định)", "d = {\"a\": 1, \"b\": 2, \"c\": 3}\nfor k in d:\n    print(k)", {}),
  ("ex", "Duyệt giá trị: values()", "d = {\"a\": 1, \"b\": 2, \"c\": 3}\nfor v in d.values():\n    print(v)\nprint(sum(d.values()))", {}),
  ("ex", "Duyệt cặp khóa - giá trị: items()", "d = {\"a\": 1, \"b\": 2}\nfor k, v in d.items():\n    print(k, v)", {}),
  ("ex", "Duyệt theo thứ tự khóa", "d = {\"cam\": 3, \"tao\": 5, \"le\": 2}\nfor k in sorted(d):\n    print(k, d[k])\nprint(sorted(d.items(), key=lambda kv: kv[1], reverse=True))   # theo giá trị giảm dần", {}),
  OP("Thao tác 4 · Thêm cặp mới"),
  ("ex", "Gán vào khóa mới", "sv = {\"ten\": \"An\"}\nsv[\"lop\"] = \"10A1\"       # khóa chưa có → thêm mới\nsv[\"tuoi\"] = 16\nprint(sv)", {}),
  ("ex", "update(): thêm nhiều cặp một lúc", "sv = {\"ten\": \"An\"}\nsv.update({\"lop\": \"10A1\", \"tuoi\": 16})\nprint(sv)", {}),
  ("ex", "setdefault(): chỉ thêm khi khóa chưa có", "d = {\"a\": 1}\nd.setdefault(\"a\", 100)    # đã có → giữ nguyên\nd.setdefault(\"b\", 2)      # chưa có → thêm\nprint(d)", {}),
  ("ex", "Xây dict từ dữ liệu: đếm tần suất", "arr = [\"cam\", \"tao\", \"cam\", \"le\", \"tao\", \"cam\"]\ndem = {}\nfor x in arr:\n    dem[x] = dem.get(x, 0) + 1     # chưa có thì coi như 0\nprint(dem)", {}),
  ("ex", "Gom nhóm: giá trị là một list", "hs = [(\"An\", \"10A1\"), (\"Binh\", \"10A2\"), (\"Chi\", \"10A1\")]\nnhom = {}\nfor ten, lop in hs:\n    nhom.setdefault(lop, []).append(ten)\nprint(nhom)", {}),
  OP("Thao tác 5 · Thay đổi giá trị"),
  ("ex", "Gán lại giá trị cho khóa đã có", "sv = {\"ten\": \"An\", \"tuoi\": 16}\nsv[\"tuoi\"] = 17          # khóa đã có → ghi đè giá trị\nsv[\"tuoi\"] += 1          # cập nhật theo giá trị cũ\nprint(sv)", {}),
  ("ex", "Đổi giá trị của mọi khóa", "gia = {\"cam\": 10, \"tao\": 20}\nfor k in gia:\n    gia[k] = gia[k] * 2     # tăng giá gấp đôi\nprint(gia)", {}),
  ("tip", "Dùng chung một cú pháp `d[k] = v` cho cả **thêm mới** lẫn **sửa**: khóa chưa có thì thêm, đã có thì ghi đè."),
  OP("Thao tác 6 · Xóa phần tử"),
  ("ex", "pop(): xóa và lấy giá trị ra", "d = {\"a\": 1, \"b\": 2, \"c\": 3}\nv = d.pop(\"a\")\nprint(v, d)\nprint(d.pop(\"z\", \"khong co\"))    # có giá trị mặc định thì không báo lỗi", {}),
  ("ex", "del và clear()", "d = {\"a\": 1, \"b\": 2, \"c\": 3}\ndel d[\"b\"]\nprint(d)\nd.clear()\nprint(d)", {}),
  ("ex", "Xóa mọi cặp thỏa điều kiện (tạo dict mới)", "diem = {\"An\": 8, \"Binh\": 4, \"Chi\": 9, \"Dung\": 3}\ndau = {k: v for k, v in diem.items() if v >= 5}\nprint(dau)", {}),
  ("warn", "Không thêm/xóa khóa trong lúc đang `for k in d:` trên chính dict đó (báo `RuntimeError`). Hãy duyệt trên `list(d)` hoặc tạo dict mới."),
  OP("Thao tác 7 · Kiểm tra & tìm kiếm"),
  ("ex", "Kiểm tra khóa tồn tại: in / not in", "d = {\"a\": 1, \"b\": 2}\nprint(\"a\" in d)            # kiểm tra KHÓA\nprint(\"z\" not in d)\nprint(2 in d.values())      # kiểm tra GIÁ TRỊ\nif \"c\" not in d:\n    d[\"c\"] = 3\nprint(d)", {}),
  ("ex", "Tìm khóa có giá trị lớn nhất", "diem = {\"An\": 8, \"Binh\": 9, \"Chi\": 7}\ntot_nhat = max(diem, key=diem.get)\nprint(tot_nhat, diem[tot_nhat])", {}),
  OP("Thao tác 8 · Sao chép & gộp"),
  ("ex", "copy() và gộp hai dict", "a = {\"x\": 1, \"y\": 2}\nb = {\"y\": 20, \"z\": 30}\nc = a.copy()               # bản sao thật\ngop = a | b                # khóa trùng: lấy giá trị của b\nprint(c, gop)\na.update(b)                # gộp thẳng vào a\nprint(a)", {}),
  OP("Tổng hợp & mở rộng"),
  ("table", ["Cú pháp", "Tác dụng"], [
    ["`d[k]`", "Lấy giá trị (không có khóa: `KeyError`)"],
    ["`d.get(k, mac_dinh)`", "Lấy giá trị an toàn"],
    ["`k in d`", "Kiểm tra khóa có tồn tại"],
    ["`d.keys()` `d.values()` `d.items()`", "Các khóa / giá trị / cặp (khóa, giá trị)"],
    ["`d.pop(k)`", "Xóa khóa và trả về giá trị"],
    ["`del d[k]`", "Xóa khóa"],
    ["`d.update(d2)`", "Gộp / cập nhật nhiều cặp"],
    ["`d.setdefault(k, v)`", "Thêm `k: v` nếu `k` chưa có"],
  ]),
  ("ex", "Dict lồng nhau: danh sách học sinh", "lop = {\n    \"An\": {\"toan\": 8, \"tin\": 9},\n    \"Binh\": {\"toan\": 7, \"tin\": 10},\n}\nlop[\"An\"][\"tin\"] = 10                 # sửa điểm\nlop[\"Chi\"] = {\"toan\": 9, \"tin\": 8}      # thêm học sinh\nfor ten, d in lop.items():\n    print(ten, sum(d.values()) / len(d))", {}),
 ])
