# -*- coding: utf-8 -*-
# Cấp 2 (Cấu trúc dữ liệu) và Cấp 3 (Hàm, lỗi, tệp)

T2 = [
dict(id="str", level=2, title="Chuỗi (str)", summary="Chuỗi là dãy ký tự **không thể sửa tại chỗ**. Chỉ số bắt đầu từ `0`; chỉ số âm đếm từ cuối.",
 blocks=[
  ("ex", "Chỉ số và độ dài", "s = \"Python\"\nprint(len(s))      # 6\nprint(s[0], s[-1])  # P n", {}),
  ("ex", "Cắt lát s[start:stop:step]", "s = \"0123456789\"\nprint(s[:4])      # 0123 (4 ký tự đầu)\nprint(s[-3:])     # 789 (3 ký tự cuối)\nprint(s[2:6])     # 2345\nprint(s[::2])     # 02468 (bước 2)\nprint(s[::-1])    # đảo ngược chuỗi", {}),
  ("table", ["Phương thức", "Tác dụng", "Ví dụ → kết quả"], [
    ["`.strip()`", "Xóa khoảng trắng hai đầu", "`\" a \".strip()` → `\"a\"`"],
    ["`.lower()` `.upper()`", "Chữ thường / HOA", "`\"Ab\".upper()` → `\"AB\"`"],
    ["`.title()` `.capitalize()`", "Hoa chữ đầu mỗi từ / chữ đầu", "`\"an binh\".title()` → `\"An Binh\"`"],
    ["`.split()`", "Tách thành list các từ", "`\"a b\".split()` → `['a', 'b']`"],
    ["`\"-\".join(list)`", "Nối list thành chuỗi", "`\"-\".join(['a','b'])` → `\"a-b\"`"],
    ["`.replace(a, b)`", "Thay a bằng b", "`\"aab\".replace(\"a\",\"x\")` → `\"xxb\"`"],
    ["`.find(x)`", "Vị trí đầu tiên (không thấy: `-1`)", "`\"hello\".find(\"l\")` → `2`"],
    ["`.count(x)`", "Đếm số lần xuất hiện", "`\"banana\".count(\"a\")` → `3`"],
    ["`.startswith(x)` `.endswith(x)`", "Bắt đầu / kết thúc bằng x", "`\"abc\".startswith(\"a\")` → `True`"],
    ["`.isdigit()` `.isalpha()`", "Toàn chữ số / toàn chữ cái", "`\"123\".isdigit()` → `True`"],
  ]),
  ("ex", "Chuẩn hóa họ tên", "ten = \"  nGUYEN   van   an \"\nprint(\" \".join(w.capitalize() for w in ten.split()))", {}),
  ("ex", "Kiểm tra chuỗi đối xứng (Palindrome)", "s = \"Madam\".lower()\nprint(s == s[::-1])", {}),
  ("ex", "Duyệt từng ký tự và đếm", "s = \"banana\"\ndem = 0\nfor ch in s:\n    if ch == \"a\":\n        dem += 1\nprint(dem)", {}),
  ("warn", "Chuỗi bất biến: `s[0] = \"X\"` gây lỗi `TypeError`. Muốn đổi phải tạo chuỗi mới: `s = \"X\" + s[1:]`."),
 ]),
dict(id="list", level=2, title="Danh sách (list)", summary="List là dãy có thứ tự, **sửa được**, chứa nhiều kiểu dữ liệu. Cắt lát giống chuỗi.",
 blocks=[
  ("ex", "Tạo, truy cập, sửa", "a = [5, 2, 9, 1]\nprint(a[0], a[-1], len(a))\na[1] = 99\nprint(a)\nprint(a[1:3])", {}),
  ("table", ["Phương thức", "Tác dụng", "Độ phức tạp"], [
    ["`.append(x)`", "Thêm x vào cuối", "O(1)"],
    ["`.insert(i, x)`", "Chèn x vào vị trí i", "O(N)"],
    ["`.pop()` / `.pop(i)`", "Xóa & trả về phần tử cuối / tại i", "O(1) / O(N)"],
    ["`.remove(x)`", "Xóa phần tử x đầu tiên", "O(N)"],
    ["`.index(x)`", "Vị trí của x (không có: báo lỗi)", "O(N)"],
    ["`.count(x)`", "Đếm số lần x xuất hiện", "O(N)"],
    ["`.sort()`", "Sắp xếp tại chỗ", "O(N log N)"],
    ["`.reverse()`", "Đảo ngược tại chỗ", "O(N)"],
    ["`sorted(a)`", "Trả về list mới đã sắp xếp", "O(N log N)"],
  ]),
  ("ex", "Thêm, xóa", "a = [1, 2, 3]\na.append(4)\na.insert(0, 0)\nprint(a)\na.remove(2)\nlast = a.pop()\nprint(a, last)", {}),
  ("ex", "Hàm thống kê có sẵn", "a = [5, 2, 9, 1, 5]\nprint(len(a), sum(a), min(a), max(a))\nprint(5 in a, a.count(5))", {}),
  ("ex", "Sắp xếp", "a = [5, 2, 9, 1]\nprint(sorted(a))                 # tăng dần, a không đổi\nprint(sorted(a, reverse=True))   # giảm dần\na.sort()\nprint(a)", {}),
  ("ex", "Sắp xếp theo tiêu chí riêng (key)", "ten = [\"binh\", \"an\", \"cuong\"]\nten.sort(key=len)               # theo độ dài\nprint(ten)", {}),
  ("ex", "Danh sách 2 chiều (ma trận)", "m = [[1, 2, 3], [4, 5, 6]]\nprint(m[1][2])        # hàng 1, cột 2\nfor hang in m:\n    print(*hang)\nm0 = [[0] * 3 for _ in range(2)]   # ma trận 2x3 toàn số 0\nprint(m0)", {}),
  ("warn", "Sao chép list: `b = a` **không** tạo bản sao (cùng một danh sách). Dùng `b = a.copy()` hoặc `b = a[:]`."),
  ("warn", "Ma trận: **không** viết `[[0] * 3] * 2` (các hàng dùng chung). Hãy dùng `[[0] * 3 for _ in range(2)]`."),
 ]),
dict(id="tupleset", level=2, title="Tuple & Set", summary="**Tuple** `( )` là bộ bất biến. **Set** `{ }` là tập hợp không trùng lặp, kiểm tra `in` rất nhanh O(1).",
 blocks=[
  ("ex", "Tuple: đóng gói, giải nén", "p = (10, 20)\nx, y = p\nprint(x, y, p[0])\n# p[0] = 5   # lỗi: tuple không sửa được", {}),
  ("ex", "Set: loại phần tử trùng", "ids = [101, 102, 101, 103, 102]\nprint(set(ids))\nprint(len(set(ids)))        # số phần tử khác nhau", {}),
  ("ex", "Phép toán tập hợp", "A = {1, 2, 3, 4}\nB = {3, 4, 5, 6}\nprint(A | B)   # hợp\nprint(A & B)   # giao\nprint(A - B)   # hiệu\nprint(A ^ B)   # hiệu đối xứng", {}),
  ("ex", "Thêm, xóa, kiểm tra", "s = {1, 2}\ns.add(3)\ns.discard(1)\nprint(s, 3 in s)", {}),
  ("tip", "Set không có thứ tự nên **không có chỉ số** `s[0]`. Cần đếm số phần tử khác nhau → dùng `len(set(a))`."),
 ]),
dict(id="dict", level=2, title="Từ điển (dict)", summary="Lưu cặp **khóa → giá trị**. Tra cứu theo khóa rất nhanh O(1).",
 blocks=[
  ("ex", "Tạo và truy cập", "sv = {\"ten\": \"An\", \"tuoi\": 16}\nprint(sv[\"ten\"])\nsv[\"lop\"] = \"10A1\"     # thêm / sửa\nprint(sv)", {}),
  ("table", ["Cú pháp", "Tác dụng"], [
    ["`d[k]`", "Lấy giá trị (không có khóa: `KeyError`)"],
    ["`d.get(k, mac_dinh)`", "Lấy giá trị an toàn"],
    ["`k in d`", "Kiểm tra khóa có tồn tại"],
    ["`d.keys()` `d.values()` `d.items()`", "Các khóa / giá trị / cặp (khóa, giá trị)"],
    ["`d.pop(k)`", "Xóa khóa và trả về giá trị"],
    ["`del d[k]`", "Xóa khóa"],
  ]),
  ("ex", "Duyệt key, value", "d = {\"a\": 1, \"b\": 2}\nfor k, v in d.items():\n    print(k, v)", {}),
  ("ex", "Đếm tần suất xuất hiện", "arr = [\"cam\", \"tao\", \"cam\", \"le\", \"tao\", \"cam\"]\ndem = {}\nfor x in arr:\n    dem[x] = dem.get(x, 0) + 1\nprint(dem)", {}),
  ("ex", "Lấy giá trị an toàn với get()", "d = {\"a\": 1}\nprint(d.get(\"b\", 0))     # không có khóa -> 0, không báo lỗi", {}),
 ]),
]

T3 = [
dict(id="func", level=3, title="Hàm (def)", summary="Hàm là khối lệnh có tên, **viết một lần dùng nhiều lần**. `return` trả kết quả về nơi gọi.",
 blocks=[
  ("ex", "Hàm có tham số và return", "def tong(a, b):\n    return a + b\n\nprint(tong(3, 4))\nkq = tong(10, 20)\nprint(kq * 2)", {}),
  ("ex", "Tham số mặc định", "def chao(ten, loi=\"Xin chao\"):\n    return f\"{loi}, {ten}!\"\n\nprint(chao(\"An\"))\nprint(chao(\"An\", \"Hello\"))", {}),
  ("ex", "Trả về nhiều giá trị (tuple)", "def min_max(a):\n    return min(a), max(a)\n\nnho, lon = min_max([5, 2, 9])\nprint(nho, lon)", {}),
  ("ex", "Hàm kiểm tra: trả về True / False", "def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n\nprint([x for x in range(20) if is_prime(x)])", {}),
  ("ex", "Phạm vi biến: biến trong hàm là biến cục bộ", "x = 10\ndef f():\n    x = 99        # biến cục bộ, không ảnh hưởng x bên ngoài\n    return x\n\nprint(f(), x)", {}),
  ("tip", "Hàm không có `return` sẽ trả về `None`. Đặt tên theo động từ: `tinh_tong`, `is_even`, `chuan_hoa`."),
 ]),
dict(id="recursion", level=3, title="Đệ quy", summary="Hàm **tự gọi chính nó**. Luôn cần **điều kiện dừng (base case)** và bước thu nhỏ bài toán.",
 blocks=[
  ("ex", "Giai thừa", "def giai_thua(n):\n    if n <= 1:          # điều kiện dừng\n        return 1\n    return n * giai_thua(n - 1)\n\nprint(giai_thua(5))", {}),
  ("ex", "Tổng 1 đến n", "def tong(n):\n    if n == 1:\n        return 1\n    return n + tong(n - 1)\n\nprint(tong(10))", {}),
  ("ex", "Fibonacci", "def fib(n):\n    if n <= 2:\n        return 1\n    return fib(n - 1) + fib(n - 2)\n\nprint([fib(i) for i in range(1, 9)])", {}),
  ("ex", "Tăng tốc đệ quy bằng bộ nhớ đệm", "from functools import lru_cache\n\n@lru_cache(maxsize=None)\ndef fib(n):\n    if n <= 2:\n        return 1\n    return fib(n - 1) + fib(n - 2)\n\nprint(fib(80))", {}),
  ("warn", "Thiếu điều kiện dừng → `RecursionError`. Python giới hạn ~1000 tầng; cần sâu hơn: `sys.setrecursionlimit(10**6)`."),
 ]),
dict(id="error", level=3, title="Xử lý lỗi try / except", summary="Bắt lỗi để chương trình **không bị dừng đột ngột** khi dữ liệu sai.",
 blocks=[
  ("ex", "Bắt lỗi nhập số", "try:\n    n = int(\"abc\")\nexcept ValueError:\n    print(\"Khong phai so!\")", {}),
  ("ex", "Nhiều loại lỗi, else, finally", "def chia(a, b):\n    try:\n        kq = a / b\n    except ZeroDivisionError:\n        print(\"Khong chia duoc cho 0\")\n    except Exception as e:\n        print(\"Loi khac:\", e)\n    else:\n        print(\"Ket qua:\", kq)\n    finally:\n        print(\"Luon chay\")\n\nchia(10, 2)\nchia(1, 0)", {}),
  ("ex", "Nhập lại đến khi đúng", "du_lieu = [\"abc\", \"x1\", \"42\"]\nfor raw in du_lieu:\n    try:\n        n = int(raw)\n        print(\"Hop le:\", n)\n        break\n    except ValueError:\n        print(\"Sai, nhap lai\")", {}),
  ("ex", "Tự báo lỗi bằng raise", "def can_bac_hai(x):\n    if x < 0:\n        raise ValueError(\"x phai >= 0\")\n    return x ** 0.5\n\ntry:\n    can_bac_hai(-4)\nexcept ValueError as e:\n    print(\"Loi:\", e)", {}),
 ]),
dict(id="file", level=3, title="Đọc và ghi tệp", summary="Dùng `with open(...)` để tệp **tự đóng**. Chế độ: `\"r\"` đọc, `\"w\"` ghi đè, `\"a\"` ghi nối thêm.",
 blocks=[
  ("ex", "Ghi rồi đọc lại", "with open(\"ds.txt\", \"w\", encoding=\"utf-8\") as f:\n    f.write(\"An\\n\")\n    f.write(\"Binh\\n\")\n\nwith open(\"ds.txt\", \"r\", encoding=\"utf-8\") as f:\n    for dong in f:\n        print(dong.strip())", {}),
  ("ex", "Đọc toàn bộ / từng dòng", "with open(\"ds.txt\", encoding=\"utf-8\") as f:\n    noi_dung = f.read()          # toàn bộ thành một chuỗi\nprint(repr(noi_dung))\nwith open(\"ds.txt\", encoding=\"utf-8\") as f:\n    dong = f.readlines()         # list các dòng\nprint(dong)", {}),
  ("ex", "Ghi nối thêm", "with open(\"ds.txt\", \"a\", encoding=\"utf-8\") as f:\n    f.write(\"Cuong\\n\")\nprint(open(\"ds.txt\", encoding=\"utf-8\").read())", {}),
  ("tip", "Luôn thêm `encoding=\"utf-8\"` để đọc ghi tiếng Việt không bị lỗi font."),
 ]),
]
