<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>TechKidPro.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web" />
    <ProjectReference Include="..\TechKidPro.Core\TechKidPro.Core.csproj" />
  </ItemGroup>
</Project>
